print(type(5))
print(type(20.5))
print(type([1,2,3]))
print(type('Hello, World!'))
print(type("Hello, World!"))
print(type(["apple", "banana", "cherry"]))
print(type({"name" : "John", "age" : 36}))
print(type(True))
print(type(None))
